name: Check and publish frontend

on:
#  pull_request:
#    types:
#      - closed
  push:
    branches:
      - main


jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Check HTML and CSS
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: ./
          css: false

      - name: Debug env
        run: |
          echo "Token length: ${{ secrets.NETLIFY_AUTH_TOKEN }}"
          echo "Site ID length: ${{ secrets.NETLIFY_SITE_ID }}"

      - name: Deploy to Netlify
        uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Deployed from GitHub action"
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: ./Fullstack-2026-Frontend
          build_command: ""
          install_command: ""
