name: Check and publish frontend

on:
  # To prevent poor‑quality code, we normally require at least one review in GitHub.
  # For testing purposes, we have temporarily disabled this setting in GitHub.
    pull_request:
      types:
        - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Check HTML and CSS
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: ./
          css: true

      - name: Deploy to Netlify
        uses: lwojcik/github-action-deploy-static-site@v1
        with:
          platform: netlify
          netlify_deploy_hook_url: ${{ secrets.NETLIFY_DEPLOY_HOOK_URL }}

